services:
  entity_graph_api:
    build:
      context: .
      dockerfile: ./src/entity_graph_api/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      API_PORT: ${API_PORT:-8000}
      DEBUG: ${DEBUG:-true}
      LOG_LEVEL: ${LOG_LEVEL}
      PYTHONPATH: /app:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/live"]
      interval: 1m
      timeout: 10s
      retries: 10
      start_period: 30s
    command: poetry run uvicorn entity_graph_api.main:app --host 0.0.0.0 --port 8000 --log-level ${LOG_LEVEL:-debug} --reload
